names_list = [
"Hugo Lloris ",
"Benoît Costil ",
"Alphonse Areola ",
"Benjamin Pavard ",
"Jules Koundé ",
"Dayot Upamecano ",
"Clément Lenglet ",
"Léo Dubois ",
"Kurt Zouma ",
"Lucas Digne ",
"Lucas Hernández ",
"Jordan Veretout ",
"Antoine Griezmann ",
"Aurélien Tchouaméni ",
"Kingsley Coman ",
"N'Golo Kanté ",
"Adrien Rabiot ",
"Mattéo Guendouzi ",
"Theo Hernández ",
"Wissam Ben Yedder ",
"Kylian Mbappé ",
"Karim Benzema ",
"Moussa Diaby "
            ]
